### ISSUE TITLE
Progress bar is producing multiple lines

### ISSUE THREAD

**Issue by amazingrando** [emulsify-ds/emulsify-cli#38]
## Expected Behavior

The progress bars shown in the attached image should be a single progress bar.

## Your Environment

- Operating System and version (desktop or mobile): macOS Monteray
- ZSH shell

<img width="1083" alt="CleanShot 2021-11-11 at 16 20 06@2x" src="https://user-images.githubusercontent.com/409903/141372184-34023c4f-47b8-4fbe-932a-48ac9b05c024.png">

**Comment by JeffTomlinson** [comment]
Known issue with node-progress:

https://github.com/visionmedia/node-progress/issues/84
