### ISSUE TITLE
Can't update to a new version of a system

### ISSUE THREAD

**Issue by ModulesUnraveled** [emulsify-ds/emulsify-cli#71]
### Need:
There needs to be a way to specify and install a new system version after initial install. So that a project can update from v1.7.0 to v1.8.0 to get new components, for example.

### Issue
Something wonky is happening when we install systems... we're choosing a version, and it's being captured in the `project.emulsify.json` file. But once it's installed, it doesn't seem to care about that file for subsequent CLI calls.

## Steps to reproduce
- [ ] Create a drupal project `composer create-project drupal/recommended-project cli-update`
- [ ] Initialize a theme `emulsify init "My Theme"
- [ ] cd into the theme `cd web/themes/custom/my_theme`
- [ ] Install a system `emulsify system install --repository https://github.com/yalesites-org/component-library-twig.git --checkout v1.7.0`
- [ ] Verify you do not have access to the "accordion" component (it's not in the list when you run `emulsify component list`)
- [ ] Edit the theme's `project.emulsify.json` and change the "checkout" from `v1.7.0` to `v1.8.0`
- [ ] Verify you still don't have access to the "accordion" component (even though it is included with v1.8.0) `emulsify component list`
- [ ] Delete your systems cache `rm -rf ~/.emulsify/cache/systems/*`
- [ ] Verify you now DO have access to the accordion component `emulsify component list`
- [ ] Edit the theme's `project.emulsify.json` and change the "checkout" from `v1.8.0` back to `v1.7.0`
- [ ] Verify you still have access to the accordion (even though you shouldn't because you're back to v1.7.0) `emulsify component list`

**Comment by nJim** [comment]
I got to know the caching system today and I'm not sure things are organized in the way it was originally described to me. I currently have two different projects using systems and my cache looks like the following:l
```bash
.emulsify/cache/systems
└─ c656a5b0792df7a582b08457c57da8d7/
         └─ component-library-twig
                 └─ all the files
└─ 03d503c875cbc9f07b44a9aed0680f1e/
         └─ component-library-twig
                 └─ all the files
```
The cache is organized by the md5 hash. This value represents the location of the project path. For example, my project located at `/home/jim/sites/emulsify/cli-update/web/themes/custom/my_theme/project.emulsify.json` becomes `03d503c875cbc9f07b44a9aed0680f1e`.

I have two questions before proposing a solution:
1. **Should projects be able to share cached systems?** Currently, every project has its own cache as shown with the md5 hash example above. If I'm working on multiple projects (different locations on my hard drive) then emulsify-cli will make a cached copy for each one. This differs from what I think was originally explained to me. It's likely safer to not share resources between projects.
2. **Should multiple versions of a system be allowed?** Currently, the version/tag is not used to organize the cached systems. We could add an extra folder. But does this even make sense? If I was working on version 1.7 and now I'm on 1.8, then do I even want to keep 1.7 around anymore?
3. Can a project have multiple systems? In the example above `component-library-twig` is a sub folder of the hashed project. Can there be multiple system in this space? I thought that the installer fails if you tried to add more than one.
