### ISSUE TITLE
Private systems?

### ISSUE THREAD

**Issue by ModulesUnraveled** [emulsify-ds/emulsify-cli#72]
@patrickocoffeyo can we host systems in a private GitHub repo?

**Comment by calebtr-metro** [comment]
I have no problems hosting a private system in github, authenticating with ssh.

**Comment by patrickocoffeyo** [comment]
@ModulesUnraveled Yes, that is definitely possible. As @calebtr-metro said, as long as the person installing the system is able to authenticate and is authorized to access the repository containing the system, there should be no problems.

**Comment by ModulesUnraveled** [comment]
Sweet! Thanks for the update
