### ISSUE TITLE
How to initialize Emulsify on an existing theme project?

### ISSUE THREAD

**Issue by johnludena** [emulsify-ds/emulsify-cli#90]
Hey y'all. I'm taking Emulsify out for a test drive but I'm having some issues with how to install all existing Compound components.

I've gone through the documentation and initializing a NEW theme project works like a charm. However, I've inherited an existing Drupal theme project that uses Emulsify but I don't see anywhere where it shows how to "initialize" an existing project and install all component files inside the "components" folder (it's currently empty). I've tried running 'emulsify system install compound' but I get the following error:

"ERROR  No Emulsify project detected. You must run this command within an existing Emulsify project. For more information about creating Emulsify projects, run "emulsify init --help"

Hope somebody can throw me a rope here. :)

**Comment by amazingrando** [comment]
I'm closing this issue. If this issue should still be active, reopen and ping me, @amazingrando.
